"""create user authenticator by password

Revision ID: 0003
Revises: 0002
Create Date: 2024-01-08 11:04:37.527356

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_authenticator",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_account", sa.String(length=32), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("password_updated_at", sa.DateTime(), nullable=False),
        sa.Column("refresh_token", sa.String(length=128), nullable=False),
        sa.Column("refresh_token_expired_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_authenticator_user_account"),
        "password_authenticator",
        ["user_account"],
        unique=False,
    )
    op.create_index(op.f("ix_password_authenticator_user_id"), "password_authenticator", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_password_authenticator_user_id"), table_name="password_authenticator")
    op.drop_index(op.f("ix_password_authenticator_user_account"), table_name="password_authenticator")
    op.drop_table("password_authenticator")
    # ### end Alembic commands ###
