"""create certification table

Revision ID: 0005
Revises: 0004
Create Date: 2024-01-09 17:32:08.097712

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: Union[str, None] = "0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("certification_type", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("gender", sa.String(length=8), nullable=False),
        sa.Column("birth", sa.Date(), nullable=False),
        sa.Column("unique_key", sa.String(length=32), nullable=False),
        sa.Column("unique_in_site", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_certification_unique_in_site"), "certification", ["unique_in_site"], unique=False)
    op.create_index(op.f("ix_certification_unique_key"), "certification", ["unique_key"], unique=False)
    op.create_index(op.f("ix_certification_user_id"), "certification", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_certification_user_id"), table_name="certification")
    op.drop_index(op.f("ix_certification_unique_key"), table_name="certification")
    op.drop_index(op.f("ix_certification_unique_in_site"), table_name="certification")
    op.drop_table("certification")
    # ### end Alembic commands ###
