"""add terms fields to user table

Revision ID: 0008
Revises: 0007
Create Date: 2024-01-10 17:04:30.140450

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: Union[str, None] = "0007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("privacy_policy_agreed_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("service_policy_agreed_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("marketing_policy_agreed_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("push_agreed_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "push_agreed_at")
    op.drop_column("user", "marketing_policy_agreed_at")
    op.drop_column("user", "service_policy_agreed_at")
    op.drop_column("user", "privacy_policy_agreed_at")
    # ### end Alembic commands ###
