"""create SchoolStudent table

Revision ID: 0010
Revises: 0009
Create Date: 2024-01-16 14:20:47.418944

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: Union[str, None] = "0009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "school_member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("school_code", sa.String(length=8), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_school_member_school_code"), "school_member", ["school_code"], unique=False)
    op.create_index(op.f("ix_school_member_user_id"), "school_member", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_school_member_user_id"), table_name="school_member")
    op.drop_index(op.f("ix_school_member_school_code"), table_name="school_member")
    op.drop_table("school_member")
    # ### end Alembic commands ###
