"""create SchoolMemberCount table

Revision ID: 0011
Revises: 0010
Create Date: 2024-01-16 16:52:51.060603

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: Union[str, None] = "0010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "school_member_count",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("school_code", sa.String(length=8), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=False),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_code", "grade", name="school_grade_uc"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("school_member_count")
    # ### end Alembic commands ###
