"""create queue item table

Revision ID: 0012
Revises: 0011
Create Date: 2024-01-18 00:15:37.698505

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: Union[str, None] = "0011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queue_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rejected_at", sa.DateTime(), nullable=True),
        sa.Column("school_code", sa.String(length=8), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=32), nullable=False),
        sa.Column("content", sa.String(length=280), nullable=True),
        sa.Column("writer_user_id", sa.Integer(), nullable=False),
        sa.Column("writer_random_nickname", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_queue_item_writer_user_id"), "queue_item", ["writer_user_id"], unique=False)
    op.create_index("queue_item_per_user_idx", "queue_item", ["writer_user_id", "school_code", "grade"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("queue_item_per_user_idx", table_name="queue_item")
    op.drop_index(op.f("ix_queue_item_writer_user_id"), table_name="queue_item")
    op.drop_table("queue_item")
    # ### end Alembic commands ###
