"""create public post table

Revision ID: 0013
Revises: 0012
Create Date: 2024-01-21 15:57:26.956357

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0013"
down_revision: Union[str, None] = "0012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "public_post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("school_code", sa.String(length=8), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=32), nullable=False),
        sa.Column("content", sa.String(length=280), nullable=True),
        sa.Column("writer_user_id", sa.Integer(), nullable=False),
        sa.Column("writer_random_nickname", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_public_post_writer_user_id"), "public_post", ["writer_user_id"], unique=False)
    op.create_index("public_post_idx", "public_post", ["id", "school_code", "grade"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("public_post_idx", table_name="public_post")
    op.drop_index(op.f("ix_public_post_writer_user_id"), table_name="public_post")
    op.drop_table("public_post")
    # ### end Alembic commands ###
