name: (Prod) Deploy to AWS Lambda

on: ["workflow_dispatch"]

permissions:
  id-token: write
  contents: read

env:
  ENV: prod

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::705007726371:role/second_prod_github_role
          aws-region: ap-northeast-2

      - name: Main Build
        run: |
          make env="${{ env.ENV }}" main_api_function_zip

      - name: Deploy main function
        run: |
          aws lambda update-function-code --function-name second_prod_lambda --zip-file fileb://api_lambda.zip

      - name: Admin Build
        run: |
          make env="${{ env.ENV }}" admin_api_function_zip

      - name: Deploy admin function
        run: |
          aws lambda update-function-code --function-name second_dev_admin_lambda --zip-file fileb://admin_api_lambda.zip
